### ISSUE TITLE
PackedFiles need to be sorted on save.

### ISSUE THREAD

**Issue by Frodo45127** [TotalWar-Modding/tw_pack_lib#2]
This comes from a bug report from RPFM. Turns out that, if the PackedFiles in a mod are not alphabetically sorted by path, the game may or may not crash when starting with the mod enabled (it triggers for some people, not for everyone). Basically, they need to be sorted on save.

**Comment by Trolldemorted** [comment]
Fascinating! Will take care of it, I won't be home over the weekend, but maybe I'll get it done this evening.

**Comment by Frodo45127** [comment]
Guess this can be closed with the PR for this accepted.
