### ISSUE TITLE
PFH4 Encrypted PackedFiles data is not padded.

### ISSUE THREAD

**Issue by Frodo45127** [TotalWar-Modding/tw_pack_lib#4]
The current logic for decrypting PackedFile's data is valid for PFH5 PackFiles, but in PFH4 PackFiles it doesn't work, as they are not padded and the extraction crashes. Tested with Rome 2 music PackFiles. For now, RPFM has a workaround using the old decrypt function that doesn't take padding into account for those PackedFiles, but that's something that needs to be fixed here.

**Comment by Trolldemorted** [comment]
Does it always crash for you, and which version are you on? I tested it right now with 0.1.18 and rome2's music.pack, and it didn't crash so far.

**Comment by Frodo45127** [comment]
nvm, turns out the function I have in RPFM for decrypting wasn't up to date and crashed in a assert. Using the last one from here seems to work.
